### ISSUE TITLE
Okta Self-Registration

### ISSUE THREAD

**Issue by byoungchanjang** [oktadeveloper/okta-nodejs-sql-server-example#1]
Hi! 

Just wanted to let you know that there is a bug in enabling self-registration when I use chrome as a browser. It says ‘This field cannot be left blank’ in red, even though it’s not blank (and it’s not even supposed to be a password field). That was with Chrome, I tested opening the same page in Firefox and it worked flawlessly.

p.s. I love Brave browser.

**Comment by reverentgeek** [comment]
Hi! I just checked and it appears to be working for me in Chrome. Can you post a screen shot of the entire form with the error message? Maybe there's another field that's causing the validation error. I'll pass it along.

**Comment by byoungchanjang** [comment]
Hi! I went back and checked and it turns out it wasn't the browser issue. I am using LastPass extension, and it was creating the problem. No problem on your side!

**Comment by reverentgeek** [comment]
👍
